spring:
  output:
    ansi:
      anabled: DETECT

server:
  port: 7779
  connection-timeout: 5000

visitlog.enabled: true

schedul:
  initialDelay: 10
  period: 120
  profileHost: localhost:7779

logging:
  level:
    com.dragon.shadowsocks: debug